.\" man page create by R# package system.
.TH NRRD 1 2000-Jan "write.ply" "write.ply"
.SH NAME
write.ply \- write the NRRD raster data to PLY point cloud model
.SH SYNOPSIS
\fIwrite.ply(\fBraster\fR as <generic> RasterPointCloud, 
\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
write the NRRD raster data to PLY point cloud model
.PP
.SH OPTIONS
.PP
\fBraster\fB \fR\- A 3 space dimension NRRD raster object. 
.PP
.PP
\fBfile\fB \fR\- file to the ply file target. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
NRRD
.SH FILES
.PP
NRRD.dll
.PP
